import { describe, expect, it } from "@jest/globals";
import { computeLegGreeks } from "../../src/utils/black-scholes.ts";
import { computeFractionalDte } from "../../src/utils/option-time.ts";

// Raw stored quotes joined to the matching chain and same-minute spot open.
// Expected values were read from Parquet FLOAT columns, not generated by this test.
// Recipe: docs/market-data.md#computed-option-greeks-method.
const fixtures = [
  {
    ticker: "IWM260319C00244000",
    date: "2026-03-19",
    time: "10:00",
    bid: 1.69,
    ask: 1.72,
    mid: 1.705,
    underlyingPrice: 244.88,
    strike: 244,
    expiration: "2026-03-19",
    contractType: "C" as const,
    greeksRevision: 3,
    rateValue: 0.0362,
    model: "bs",
    dte: 0.25,
    expected: {
      delta: 0.617210328578949,
      gamma: 0.12550921738147736,
      theta: -2.3055925369262695,
      vega: 0.024455828592181206,
      iv: 0.4744090735912323,
    },
  },
  {
    ticker: "IWM260319C00246000",
    date: "2026-03-19",
    time: "15:00",
    bid: 0.81,
    ask: 0.84,
    mid: 0.825,
    underlyingPrice: 246.59,
    strike: 246,
    expiration: "2026-03-19",
    contractType: "C" as const,
    greeksRevision: 3,
    rateValue: 0.0362,
    model: "bachelier",
    dte: 1 / 24,
    expected: {
      delta: 0.6913829445838928,
      gamma: 0.29774749279022217,
      theta: -4.9964728355407715,
      vega: 3.761981861316599e-5,
      iv: 110.68090057373047,
    },
  },
];

describe("documented computed-Greeks recipe on stored revision-3 rows", () => {
  it.each(fixtures)("reproduces $ticker at $time ($model)", (row) => {
    const dte = computeFractionalDte(row.date, row.time, row.expiration);
    expect(dte).toBe(row.dte);
    const result = computeLegGreeks(
      (row.bid + row.ask) / 2,
      row.underlyingPrice,
      row.strike,
      dte,
      row.contractType,
      row.rateValue,
      0,
    );
    expect(result.model).toBe(row.model);
    for (const greek of ["delta", "gamma", "theta", "vega", "iv"] as const) {
      expect(result[greek]).not.toBeNull();
      // Binary32 rounding has <= 2^-24 relative error for normal values.
      // 2^-23 leaves one additional rounding margin; no loose absolute floor.
      expect(Math.abs(result[greek]! - row.expected[greek])).toBeLessThanOrEqual(
        Math.abs(row.expected[greek]) * 2 ** -23,
      );
    }
  });

  // The documented model rule: dte < 0.1 → Bachelier, dte >= 0.1 → Black-Scholes.
  it.each([
    { time: "13:36", dte: 0.1, model: "bs" },
    { time: "13:37", dte: 143 / 1440, model: "bachelier" },
  ])("selects $model at same-day $time", ({ time, dte, model }) => {
    const actualDte = computeFractionalDte("2026-03-19", time, "2026-03-19");
    expect(actualDte).toBe(dte);
    expect(computeLegGreeks(0.825, 246.59, 246, actualDte, "C", 0.0362, 0).model).toBe(model);
  });
});
